cd 1raw
wget http://coolrom.com/roms/$@/0
wget http://coolrom.com/roms/$@/a
wget http://coolrom.com/roms/$@/b
wget http://coolrom.com/roms/$@/c
wget http://coolrom.com/roms/$@/d
wget http://coolrom.com/roms/$@/e
wget http://coolrom.com/roms/$@/f
wget http://coolrom.com/roms/$@/g
wget http://coolrom.com/roms/$@/h
wget http://coolrom.com/roms/$@/i
wget http://coolrom.com/roms/$@/j
wget http://coolrom.com/roms/$@/k
wget http://coolrom.com/roms/$@/l
wget http://coolrom.com/roms/$@/m
wget http://coolrom.com/roms/$@/n
wget http://coolrom.com/roms/$@/o
wget http://coolrom.com/roms/$@/p
wget http://coolrom.com/roms/$@/q
wget http://coolrom.com/roms/$@/r
wget http://coolrom.com/roms/$@/s
wget http://coolrom.com/roms/$@/t
wget http://coolrom.com/roms/$@/u
wget http://coolrom.com/roms/$@/v
wget http://coolrom.com/roms/$@/w
wget http://coolrom.com/roms/$@/x
wget http://coolrom.com/roms/$@/y
wget http://coolrom.com/roms/$@/z
cd ..
